# Packfire Framework
#
# this file provides configuration for Travis Continuous Integration
# See Packfire on TravisCI at http://travis-ci.org/packfire/framework

language: php
php:
  - 5.3
  - 5.3.3
  - 5.4
env:
  - databasePassword=""
script: sh packfire.sh test