#
# YAML Configuration File - routing
#     Routing for the application goes here
#
# Author      : Sam-Mauris Yong / mauris@hotmail.sg
# Copyright   : Copyright (c) 2010-2012, Sam-Mauris Yong
# License     : http://www.opensource.org/licenses/bsd-license New BSD License
#

---

welcome:
  rewrite: "/"
  actual: "view.pSetupWelcomeView"

installAct:
  rewrite: "/install"
  method: post
  actual: "controller.pSetupController:installFramework"
  params:
    root: (.*)
  
installView:
  rewrite: "/install"
  method: get
  actual: "view.pSetupInstallView"
  
createAct:
  rewrite: "/create"
  method: post
  actual: "controller.pSetupController:createApplication"
  params:
    root: (.*)
    packfire: (.*)
  
createView:
  rewrite: "/create"
  method: get
  actual: "view.pSetupCreateView"

...